name: Lint Go Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' 

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2  
          args: --timeout=5m  